name: Build MacOS App Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure to include ntcore and other dependencies in requirements.txt

    - name: Create App Image
      run: |
        # Add commands to create your app image
        # Example using pyinstaller to create an app
        pip install pyinstaller  # or any other packaging tool you're using
        pyinstaller --onefile your_script.py  # Adjust as necessary

    - name: Archive app image
      run: |
        mkdir -p output
        cp dist/your_script.app output/  # Adjust according to your build
        echo "App image created and saved to output folder."

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-app-image
        path: output/your_script.app  # Adjust according to your build
